#!/usr/bin/env python
#coding=utf-8

import urllib3
import json
from pprint import pprint
from collections import OrderedDict
http = urllib3.PoolManager()
url = "https://iptv-org.github.io/iptv/channels.json"
data1dict = {}
realurl = url
urlread = http.request('GET', realurl)
datadict = json.loads(urlread.data)


for i in datadict:
    data1dict.update(i)
    if data1dict['category'] == "XXX":
        print("%s:%s"%("名称",data1dict['name']))
        print("%s:%s"%("URL",data1dict['url']))  
