#!/usr/bin/env python
#coding=utf-8

import os
import pathlib
import socket

IP = socket.gethostbyname(socket.gethostname())
redisconf = open("/data/redis-3.2.9/redis.conf","r")
str = redisconf.read()
conffinish = open("/data/redis-3.2.9/redis.conf","w")

chkdsk = pathlib.Path("/data/redis-3.2.9.tar")
chkfile = chkdsk.is_file()
print "%s:   %s" % ("found redis.tar is",chkfile)
if chkfile:
    print "yes"
    os.system("tar xf /data/redis-3.2.9.tar")
    ipchange = str.replace("127.0.0.1","127.0.0.1"+IP)
    conffinish.write(ipchange)
    conffinish.close()
    print "change IP to "+IP
else:
    print "no"
